@startuml Z009
!include include/_posparam.plantuml

$rectanglePOS("Z009", "Strategic Management", "red", "Z" ) {
    $rectanglePOS("Q0055", "Innovation", "red", "Q")
    $rectanglePOS("Q0056", "Business Plan", "red", "Q")
}

@enduml

@startuml Z006
!include include/_posparam.plantuml

$rectanglePOS("Z006", "Customer marketing and CRM", "green", "Z" ) {
    $rectanglePOS("Q0032", "Loyalty", "green", "Q") {
        $rectanglePOS($name="Client", $type="package", $instance="0") {
            $rectanglePOS($soluqiqID="CO_APP_047", $name="Customer Benefits", $zoneColor="#LightSlateGrey", $level="Z", $instance="1", $iconic="<&account-logout>", $fullname="COMARCH - Customer Diamond Benefits & Loyalty")
        }
    }
    $rectanglePOS("Q0033", "Incoming & outgoing Customer Interactions", "green", "Q")
    $rectanglePOS("Q0034", "Customer Account Management", "green", "Q")
}
@enduml

@startuml Z013
!include include/_posparam.plantuml

$rectanglePOS("Z013", "Sales Channel or brand", "green", "Z" ) {
    $rectanglePOS("Q0077", "Payment / Electronic banking / Tills", "green", "Q") {
        $rectanglePOS($name="POS", $type="package", $instance="0051") {
            $rectanglePOS($soluqiqID="CO_APP_005", $name="Extenda", $zoneColor="#GoldenRod", $level="Z", $instance="1", $iconic="<&battery-full>", $fullname="EXTENDA - POS")
        }
    }
    $rectanglePOS("Q0076", "Sales services (before; during; after)", "green", "Q")
    $rectanglePOS("Q0079", "Digital sales", "green", "Q"){
        $rectanglePOS("IL00098", "e-Merchandising / e-Product presentation", $level="I")
        $rectanglePOS("IL00099", "Basket & Check-out", $level="I") {
            $rectanglePOS($name="POS", $type="package", $instance="0681") {
                $rectanglePOS($soluqiqID="CO_APP_068", $name="Merchant server", $zoneColor="#Gold", $level="Z", $instance="1", $iconic="<&beaker>", $fullname="Merchant Server")
        }

        }
    }
    $rectanglePOS("Q0080", "Physical sales", "green", "Q") {
        $rectanglePOS("IL00097", "Merchandising plan", $level="I") {
            $rectanglePOS($name="Commerce", $type="package", $instance="293") {
                $rectanglePOS($name="Upstream", $type="package", $instance="293") {
                    $rectanglePOS($soluqiqID="CO_APP_029", $name="My Offer", $zoneColor="#Beige", $level="Z", $instance="3", $iconic="<&arrow-circle-top>", $fullname="MY OFFER - Permanent Offer") {
                        usecase "Build multi-format offer\nOptimisation of detention and implementation" as MyOffer1
                    }
                    $rectanglePOS($soluqiqID="CO_APP_022", $name="My Offer Tablet", $zoneColor="#AliceBlue", $level="Z", $instance="3", $iconic="<&arrow-left>", $fullname="My Offer Tablet")
                }
            }

        }
    }
}

Q00771 - Q00761
Q00771 -- Q00801
Q00761 -- Q00791
@enduml

@startuml Z010
!include include/_posparam.plantuml

$rectanglePOS("Z010", "Data Management (Data as an asset)", "brown", "Z" ) {
    $rectanglePOS("Q0086", "Third Party Data", "brown", "Q")
    $rectanglePOS("Q0087", "Gathering; storage & historization", "brown", "Q") {
        $rectanglePOS($name="Integration", $type="package", $instance="0") {
            $rectanglePOS($soluqiqID="CO_APP_036", $name="Yoda", $zoneColor="#LightSeaGreen", $level="Z", $instance="1", $iconic="<&action-undo>", $fullname="YODA - Data Exchange Platform & API Management")
        }
        $rectanglePOS($name="Client", $type="package", $instance="671") {
            $rectanglePOS($soluqiqID="CO_APP_067", $name="Odigo Customer", $zoneColor="#FloralWhite", $level="Z", $instance="1", $iconic="<&battery-empty>", $fullname="ODIGO - Customer Diamond Interaction Hub")

        }

    }
    $rectanglePOS("Q0088", "DQM & Data Reconciliation", "brown", "Q")
    $rectanglePOS("Q0089", "Data analysis & Algorithms", "brown", "Q") {
        $rectanglePOS($name="Commerce", $type="package", $instance="171") {
            $rectanglePOS($name="DownStream_Analytics_Supply", $type="package", $instance="171") {
                $rectanglePOS($soluqiqID="CO_APP_017", $name="Smart Vision", $zoneColor="#Aquamarine", $level="Z", $instance="1", $iconic="<&audio>", $fullname="GOOGLE DATA STUDIO - Smartvision") {
                    usecase "Measure performance\nFind issues root cause\nDefine goals\nData Driven Decisions " as smartvision1
                }
            }
        }
        $rectanglePOS($name="Client", $type="package", $instance="381") {
            $rectanglePOS($soluqiqID="CO_APP_038", $name="Satisfactory", $zoneColor="#DarkKhaki", $level="Z", $instance="1", $iconic="<&basket>", $fullname="SATISFACTORY - NPS Net Promoter Score")
        }
    }
    $rectanglePOS("Q0090", "Data Dictionary", "brown", "Q")
    $rectanglePOS("Q0091", "Repositories", "brown", "Q"){
        $rectanglePOS("IL00012", "Nomenclature", $level="I")
        $rectanglePOS("IL00013", "Supply Chain", $level="I")
        $rectanglePOS("IL00016", "Chart of accounts & accounting keys", $level="I")
        $rectanglePOS("IL00017", "Billing or Invoices Receivable", $level="I")
        $rectanglePOS("IL00018", "Invoices Payable", $level="I")
        $rectanglePOS("IL00115", "Customers", $level="I")
        $rectanglePOS("IL00116", "Products / Services (characteristics; media)", $level="I") {
            $rectanglePOS($name="Integration", $type="package", $instance="1") {
                $rectanglePOS($soluqiqID="CO_APP_056", $name="ODE Stock", $zoneColor="#LightGray", $level="Z", $instance="1", $iconic="<&align-center>", $fullname="ODE Stock - Operational Data Exposition")
            }
        }
        $rectanglePOS("IL00117", "Suppliers", $level="I")
        $rectanglePOS("IL00118", "Marketplace vendors", $level="I")
        $rectanglePOS("IL00119", "Partners", $level="I")
        $rectanglePOS("IL00120", "Tax & Currencies", $level="I")
        $rectanglePOS("IL00121", "Sites & Countries", $level="I")
        $rectanglePOS("IL00122", "Legal Structure", $level="I")
        $rectanglePOS("IL00123", "Persons", $level="I")
    }
    $rectanglePOS("Q0101", "KPI (calculation & exposition)", "brown", "Q") {
        $rectanglePOS($name="Consolidation", $type="package", $instance="0") {
            $rectanglePOS($soluqiqID="CO_APP_006", $name="Datapool", $zoneColor="#LightSalmon", $level="Z", $instance="1", $iconic="<&align-left>", $fullname="GOOGLE CLOUD PLATFORM - Datapool for analytics")
        }
         $rectanglePOS($name="BI", $type="package", $instance="0081") {
            $rectanglePOS($soluqiqID="CO_APP_008", $name="IPON Achat", $zoneColor="#HoneyDew", $level="Z", $instance="1", $iconic="<&bluetooth>", $fullname="IPON Purchase decisional")
            $rectanglePOS($soluqiqID="CO_APP_023", $name="IPON Promo", $zoneColor="#IndianRed", $level="Z", $instance="1", $iconic="<&bold>", $fullname="IPON Promo Decisional")
        }

    }
}

Q00911 --- Q00871
Q00911 --- Q00891 

Q01011 -- Q00861
Q01011 -- Q00901
Q01011 -- Q00881


IL000121 -- IL000131
IL000161 -- IL000171
IL000181 -- IL001181
IL001151 -- IL001201
IL001171 -- IL001221
IL001191 -- IL001231
IL001161 -- IL001211
@enduml

@startuml Z007
!include include/_posparam.plantuml

$rectanglePOS("Z007", "Offer (products & services)", "green", "Z" ) {
    $rectanglePOS("Q0040", "Partners Management", "green", "Q"){
        $rectanglePOS("IL00092", "Partner contract", $level="I")
        $rectanglePOS("IL00093", "Catalog Publication to Partners", $level="I") {
            package MasterData as MasterData4 {
                $rectanglePOS($name="Commerce", $type="package", $instance="391") {
                    $rectanglePOS($name="Upstream", $type="package", $instance="391") {
                        $rectanglePOS($soluqiqID="CO_APP_039", $name="Collector", $zoneColor="#LightSteelBlue", $level="Z", $instance="1", $iconic="<&account-login>", $fullname="COMARCH - GDSN Provider & Product Referencing") {
                            usecase "product prereferencing\nproduct referencing\nsending product to GICA / METI / Enrichment" as pr1
                        }
                    }
                }
            }
            $rectanglePOS($name="Commerce", $type="package", $instance="292") {
                $rectanglePOS($name="Upstream", $type="package", $instance="292") {
                    $rectanglePOS($soluqiqID="CO_APP_029", $name="My Offer", $zoneColor="#Beige", $level="Z", $instance="2", $iconic="<&arrow-circle-top>", $fullname="MY OFFER - Permanent Offer") {
                        usecase "Build multi-format offer\nOptimisation of detention and implementation" as MyOffer2
                    }
                    $rectanglePOS($soluqiqID="CO_APP_022", $name="My Offer Tablet", $zoneColor="#AliceBlue", $level="Z", $instance="1", $iconic="<&arrow-left>", $fullname="My Offer Tablet")

                }
            }

        }
        $rectanglePOS("IL00094", "B2B sell / Transfer pricing management", $level="I") {
            $rectanglePOS($name="Commerce", $type="package", $instance="9") {
                $rectanglePOS($name="Upstream", $type="package", $instance="5") {
                    $rectanglePOS($soluqiqID="CO_APP_024", $name="METI Central", $zoneColor="#LightPink", $level="Z", $instance="5", $iconic="<&align-right>", $fullname="METI Central") {
                        usecase "Manage commercial supplier referencing\nManage product referencing for B2B\nMastering product life cycle\nSend supplier and Product to MDM / METI" as MetiCentral6
                    }
                }
            }
        }
    }
    IL000931 -- IL000941
    IL000941 - IL000921

    $rectanglePOS("Q0041", "Product Commitment management", "green", "Q")
    $rectanglePOS("Q0042", "Offer to Customers", "green", "Q"){
        $rectanglePOS("IL00085", "Offer Definition", $level="I") {
            $rectanglePOS($name="Commerce", $type="package", $instance="291") {
                $rectanglePOS($name="Upstream", $type="package", $instance="291") {
                    $rectanglePOS($soluqiqID="CO_APP_029", $name="My Offer", $zoneColor="#Beige", $level="Z", $instance="1", $iconic="<&arrow-circle-top>", $fullname="MY OFFER - Permanent Offer") {
                        usecase "Build multi-format offer\nOptimisation of detention and implementation" as MyOffer3
                    }
                    $rectanglePOS($soluqiqID="CO_APP_022", $name="My Offer Tablet", $zoneColor="#AliceBlue", $level="Z", $instance="2", $iconic="<&arrow-left>", $fullname="My Offer Tablet")
                    $rectanglePOS($soluqiqID="CO_APP_082", $name="My Offer Opé", $zoneColor="#AntiqueWhite", $level="Z", $instance="1", $iconic="<&arrow-right>", $fullname="My Offer - Promotional offer") {
                        usecase "commercial operations management" as MyOfferOpe1
                    }

                }
            }
            CO_APP_0222 - CO_APP_0821
            $rectanglePOS($name="BI", $type="package", $instance="0091") {
                $rectanglePOS($soluqiqID="CO_APP_009", $name="IPON Offer", $zoneColor="#GhostWhite", $level="Z", $instance="2", $iconic="<&bell>", $fullname="IPON Offer decisional")
            }

        }

        $rectanglePOS("IL00086", "Vendor catalog", $level="I") {
            $rectanglePOS($name="MasterData", $type="package", $instance="9") {
                $rectanglePOS($name="Commerce", $type="package", $instance="12") {
                    $rectanglePOS($name="Upstream", $type="package", $instance="3") {
                        $rectanglePOS($soluqiqID="CO_APP_039", $name="Collector", $zoneColor="#LightSteelBlue", $level="Z", $instance="3", $iconic="<&account-login>", $fullname="COMARCH - GDSN Provider & Product Referencing") {
                            usecase "product prereferencing\nproduct referencing\nsending product to GICA / METI / Enrichment" as pr2

                        }
                    }
                }
            }
        }
        $rectanglePOS("IL00087", "Merchandising (plan)", $level="I")
        $rectanglePOS("IL00088", "Selling price management", $level="I") {
            $rectanglePOS($name="Commerce", $type="package", $instance="241") {
                $rectanglePOS($name="Upstream", $type="package", $instance="241") {
                    $rectanglePOS($soluqiqID="CO_APP_024", $name="METI Central", $zoneColor="#LightPink", $level="Z", $instance="6", $iconic="<&align-right>", $fullname="METI Central") {
                        usecase "Manage commercial supplier referencing\nManage product referencing for B2B\nMastering product life cycle\nSend supplier and Product to MDM / METI" as MetiCentral1
                    }
                    $rectanglePOS($soluqiqID="CO_APP_003", $name="Optimix", $zoneColor="#DarkSeaGreen", $level="Z", $instance="1", $iconic="<&bar-chart>", $fullname="OPTI-MIX - Pricing optimization") {
                        usecase "manage pricing policy"
                    }

                }
            }
            $rectanglePOS($name="Commerce", $type="package", $instance="4210") {
                $rectanglePOS($name="Downstream", $type="package", $instance="4210") {
                    $rectanglePOS($soluqiqID="CO_APP_042", $name="METI Store", $zoneColor="#LightPink", $level="Z", $instance="10", $iconic="<&arrow-bottom>", $fullname="METI - Retail Diamond Store")
                    $rectanglePOS($soluqiqID="CO_APP_049", $name="My Store", $zoneColor="#LightCyan", $level="Z", $instance="10", $iconic="<&arrow-circle-bottom>", $fullname="MY STORE - Mobility in store")

                }
            }

        }
        $rectanglePOS("IL00089", "Product margin management", $level="I")
        $rectanglePOS("IL00091", "Products information enrichment", $level="I"){
            $rectanglePOS($name="MasterData", $type="package", $instance="5") {
                $rectanglePOS($soluqiqID="CO_APP_016", $name="Quable", $zoneColor="#LightSkyBlue", $level="Z", $instance="2", $iconic="<&action-redo>", $fullname="QUABLE - PIM Product Information Management") {
                    usecase "Product information validation\nEnrichment" as quable2
                }
            }
    }
    IL000851 -- IL000881
    IL000881 -- IL000861
    IL000861 -- IL000911
    IL000861 - IL000871
    IL000911 - IL000891

} 
@enduml

@startuml Z015
!include include/_posparam.plantuml

$rectanglePOS("Z015", "Commercial Animation", "green", "Z" ) {
    $rectanglePOS("Q0036", "Commercial animation execution", "green", "Q")
    $rectanglePOS("Q0084", "Commercial animation development", "green", "Q")
}

@enduml
@startuml Z001
!include include/_posparam.plantuml


$rectanglePOS("Z001", "Direct and indirect purchase", "green", "Z" ) {
    $rectanglePOS("Q0104", "Indirect Purchase", "green", "Q"){
        $rectanglePOS("IL00128", "Product / Supplier referencing; Supplier negotiation; Supplicer contract management; Purchasing budget management", $level="I")
    }
    $rectanglePOS("Q0105", "Direct Purchase",  "green", "Q"){
        $rectanglePOS("IL00011", "Product Referencing", $level="I"){
            $rectanglePOS($name="MasterData", $type="package", $instance="2") {
                $rectanglePOS($name="Commerce", $type="package", $instance="5") {
                    $rectanglePOS($name="Upstream", $type="package", $instance="2") {
                        $rectanglePOS($soluqiqID="CO_APP_039", $name="Collector", $zoneColor="#LightSteelBlue", $level="Z", $instance="4", $iconic="<&account-login>", $fullname="COMARCH - GDSN Provider & Product Referencing") {
                                                        usecase "product prereferencing\nproduct referencing\nsending product to GICA / METI / Enrichment" as pr3
                        }
                        $rectanglePOS($soluqiqID="CO_APP_016", $name="Quable", $zoneColor="#LightSkyBlue", $level="Z", $instance="1", $iconic="<&action-redo>", $fullname="QUABLE - PIM Product Information Management") {
                            usecase "Product information validation\nEnrichment" as quable1
                        }
                    }
                }
            }
            $rectanglePOS($name="Commerce", $type="package", $instance="6") {
                $rectanglePOS($name="Upstream", $type="package", $instance="7") {
                    $rectanglePOS($soluqiqID="CO_APP_024", $name="METI Central", $zoneColor="#LightPink", $level="Z", $instance="7", $iconic="<&align-right>", $fullname="METI Central") {
                        usecase "Manage commercial supplier referencing\nManage product referencing for B2B\nMastering product life cycle\nSend supplier and Product to MDM / METI" as MetiCentral1
                    }
                }
            }
        }
        $rectanglePOS("IL00129", "Marketplace referencing", $level="I")
        $rectanglePOS("IL00130", "Import management", $level="I")
        $rectanglePOS("IL00131", "Purchasing budget management", $level="I")
        $rectanglePOS("IL00132", "Supplier negotiation", $level="I") {
            $rectanglePOS($name="MasterData", $type="package", $instance="392") {
                $rectanglePOS($name="Commerce", $type="package", $instance="392") {
                    $rectanglePOS($name="Upstream", $type="package", $instance="3") {
                        $rectanglePOS($soluqiqID="CO_APP_039", $name="Collector", $zoneColor="#LightSteelBlue", $level="Z", $instance="2", $iconic="<&account-login>", $fullname="COMARCH - GDSN Provider & Product Referencing") {
                                                        usecase "product prereferencing\nproduct referencing\nsending product to GICA / METI / Enrichment" as pr4
                        }
                        $rectanglePOS($soluqiqID="CO_APP_051", $name="ANEE", $zoneColor="#LightGoldenRodYellow", $level="Z", $instance="1", $iconic="<&arrow-circle-right>", $fullname="ANEE - Negociation and Management of Supplier contracts") {
                            usecase "Negotiation\nContracting\nInvoicing" as ANEE1
                        }

                    }
                }
            }
            $rectanglePOS($name="BI", $type="package", $instance="0091") {
                $rectanglePOS($soluqiqID="CO_APP_009", $name="IPON Offer", $zoneColor="#GhostWhite", $level="Z", $instance="1", $iconic="<&bell>", $fullname="IPON Offer decisional")
            }
        }
        $rectanglePOS("IL00133", "Supplier referencing", $level="I") {
            $rectanglePOS($name="Commerce", $type="package", $instance="8") {
                $rectanglePOS($name="Upstream", $type="package", $instance="1") {
                    $rectanglePOS($soluqiqID="CO_APP_024", $name="METI Central", $zoneColor="#LightPink", $level="Z", $instance="1", $iconic="<&align-right>", $fullname="METI Central") {
                        usecase "Manage commercial supplier referencing\nManage product referencing for B2B\nMastering product life cycle\nSend supplier and Product to MDM / METI" as MetiCentral2
                    }
                }
            }
        }
        $rectanglePOS("IL00134", "Product Life Cycle Management", $level="I")
        $rectanglePOS("IL00135", "Supplier contract management", $level="I") {
            $rectanglePOS($name="Commerce", $type="package", $instance="512") {
                $rectanglePOS($name="Upstream", $type="package", $instance="512") {
                    $rectanglePOS($soluqiqID="CO_APP_051", $name="ANEE", $zoneColor="#LightGoldenRodYellow", $level="Z", $instance="2", $iconic="<&arrow-circle-right>", $fullname="ANEE - Negociation and Management of Supplier contracts") {
                        usecase "Negotiation\nContracting\nInvoicing" as ANEE2
                    }

                }
            }

        }
    }
    IL000111 -- IL001321
    IL001321 -- IL001351
    IL001351 - IL001331
    IL001351 -- IL001291
    IL001351 -- IL001301
    IL001351 -- IL001341
    IL001351 -- IL001311
}   

Q01051 -- Q01041

@enduml

@startuml Z003
!include include/_posparam.plantuml

$rectanglePOS("Z003", "Product transformation / manufacturing", "green", "Z" ) {
    $rectanglePOS("Q0096", "Formulation and recipes", "green", "Q")
    $rectanglePOS("Q0097", "Manufacturing management",  "green", "Q")
    $rectanglePOS("Q0098", "Chain Management", "green", "Q")
    }

@enduml

@startuml Z004
!include include/_posparam.plantuml

$rectanglePOS("Z004", "Support", "purple", "Z" ) {
    $rectanglePOS("Q0022", "Accountability / Finance", "purple", "Q") {
        $rectanglePOS("IL00005", "Receivables Accounting", $level="I")
        $rectanglePOS("IL00006", "Payables Accounting", $level="I") {
            $rectanglePOS($name="Commerce", $type="package", $instance="513") {
                $rectanglePOS($name="Upstream", $type="package", $instance="513") {
                    $rectanglePOS($soluqiqID="CO_APP_051", $name="ANEE", $zoneColor="#LightGoldenRodYellow", $level="Z", $instance="3", $iconic="<&arrow-circle-right>", $fullname="ANEE - Negociation and Management of Supplier contracts")
                }
            }

        }
        $rectanglePOS("IL00007", "Asset Accounting", $level="I")
        $rectanglePOS("IL00008", "General Ledger Accounting & Closing", $level="I")
        $rectanglePOS("IL00009", "Cash & Treasury", $level="I")
        $rectanglePOS("IL00010", "Tax and Duties Management ", $level="I")
        $rectanglePOS("IL00014", "Task Automation ", $level="I")
        $rectanglePOS("IL00015", "Consolidation Accounting", $level="I")
    }
    IL000061 -- IL000051
    IL000051 - IL000071
    IL000071 - IL000081
    IL000051 -- IL000091
    IL000071 -- IL000101
    IL000081 -- IL000141
    IL000101 -- IL000151
    $rectanglePOS("Q0102", "Performance steering", "purple", "Q")
    $rectanglePOS("Q0023", "IT", "purple", "Q")
    $rectanglePOS("Q0024", "Legal", "purple", "Q")
    $rectanglePOS("Q0026", "HR", "purple", "Q")
    $rectanglePOS("Q0027", "Technical services", "purple", "Q")
    $rectanglePOS("Q0093", "Supervision", "purple", "Q")
    $rectanglePOS("Q0099", "Communication & Collaboration", "purple", "Q")
    $rectanglePOS("Q0103", "Supplier Administration", "purple", "Q"){
        $rectanglePOS("IL00126", "Invoice Control", $level="I") {
            $rectanglePOS($name="Commerce", $type="package", $instance="281") {
                $rectanglePOS($name="Downstream", $type="package", $instance="281") {
                    $rectanglePOS($soluqiqID="CO_APP_028", $name="METI Matching", $zoneColor="#LightPink", $level="Z", $instance="1", $iconic="<&arrow-circle-left>", $fullname="METI - Retail Diamond Invoice Matching") {
                        usecase "Reconciliation Management\n" as metimatching1
                    }
                }
            }
        }
        $rectanglePOS("IL00127", "Litigation management", $level="I") {
            $rectanglePOS($name="Commerce", $type="package", $instance="282") {
                $rectanglePOS($name="Downstream", $type="package", $instance="282") {
                    $rectanglePOS($soluqiqID="CO_APP_028", $name="METI Matching", $zoneColor="#LightPink", $level="Z", $instance="2", $iconic="<&arrow-circle-left>", $fullname="METI - Retail Diamond Invoice Matching") {
                        usecase "Reconciliation Management\n" as metimatching2
                    }
                }
            }

        }
    }
}
Q01031 -- Q01021
Q01031 -- Q00991
Q01031 -- Q00931
Q01021 -- Q00231
Q00931 -- Q00241
Q00991 -- Q00271
Q00241 -- Q00261
@enduml
@startuml Z005
!include include/_posparam.plantuml


$rectanglePOS("Z005", "Supply chain", "green", "Z" ) {
    $rectanglePOS("Q0028", "Logistics", "green", "Q"){
        $rectanglePOS("IL00001", "Handling Support Management", $level="I")
        $rectanglePOS("IL00002", "Dock Management", $level="I")
        $rectanglePOS("IL00100", "Orchestration in logistics", $level="I") {
            $rectanglePOS($name="Commerce", $type="package", $instance="531") {
                $rectanglePOS($name="Downstream", $type="package", $instance="531") {
                    $rectanglePOS($soluqiqID="CO_APP_053", $name="Tesisquare", $zoneColor="#BUSINESS", $level="Z", $instance="1", $iconic="<&ban>", $fullname="TESISQUARE - TMS Transport Management System") {
                        usecase "TMS upstream (goods receiving)\n TMS downstream (goods deliveries)" as Tesi1
                    }
                    $rectanglePOS($soluqiqID="CO_APP_001", $name="GCS Generix", $zoneColor="#Azure", $level="Z", $instance="1", $iconic="<&badge>", $fullname="GENERIX - WMS Warehouse Management System") {
                        usecase "Reception\nStorage\nPreparation\nShipments" as GCS1
                    }
                }
            }

        }
        $rectanglePOS("IL00101",  "Warehouse management", $level="I") {
            $rectanglePOS($name="Commerce", $type="package", $instance="0011") {
                $rectanglePOS($name="Downstream", $type="package", $instance="0011") {
                    $rectanglePOS($soluqiqID="CO_APP_001", $name="GCS Generix", $zoneColor="#Azure", $level="Z", $instance="2", $iconic="<&badge>", $fullname="GENERIX - WMS Warehouse Management System") {
                        usecase "Reception\nStorage\nPreparation\nShipments" as GCS2
                    }
                }
            }
        }
        $rectanglePOS("IL00102", "Transport", $level="I") {
            $rectanglePOS($name="Commerce", $type="package", $instance="532") {
                $rectanglePOS($name="Downstream", $type="package", $instance="532") {
                    $rectanglePOS($soluqiqID="CO_APP_053", $name="Tesisquare", $zoneColor="#BUSINESS", $level="Z", $instance="2", $iconic="<&ban>", $fullname="TESISQUARE - TMS Transport Management System") {
                        usecase "TMS upstream (goods receiving)\n TMS downstream (goods deliveries)" as Tesi2
                    }
                }
            }

        }

        $rectanglePOS("IL00125", "Warehouse Controlling System (WCS)", $level="I")
    }
    IL001001 -- IL001011
    IL001011 -- IL001021
    IL001021 -- IL001251
    IL001251 -- IL000011
    IL000011 -- IL000021
    

    $rectanglePOS($soluqiqID="Q0029", "Store Back-Office", "green", "Q", $instance="1") {
        $rectanglePOS("IL00103", "Receiving / Storage / shelving", $level="I") {
            $rectanglePOS($name="Commerce", $type="package", $instance="424") {
                $rectanglePOS($name="Downstream", $type="package", $instance="424") {
                    $rectanglePOS($soluqiqID="CO_APP_042", $name="METI Store", $zoneColor="#LightPink", $level="Z", $instance="4", $iconic="<&arrow-bottom>", $fullname="METI - Retail Diamond Store")
                    $rectanglePOS($soluqiqID="CO_APP_034", $name="RPE", $zoneColor="#Bisque", $level="Z", $instance="1", $iconic="<&bar-chart>", $fullname="RPE Replenishment Parameters Engine") {
                        usecase "Store resupply optimisation" as RPE1
                    }
                    $rectanglePOS($soluqiqID="CO_APP_049", $name="My Store", $zoneColor="#LightCyan", $level="Z", $instance="1", $iconic="<&arrow-circle-bottom>", $fullname="MY STORE - Mobility in store") {
                        usecase "employee efficiency in store" as mystore11
                    }
                }
            }
        }
        $rectanglePOS("IL00104", "Inter store transfer", $level="I") {
            $rectanglePOS($name="Commerce", $type="package", $instance="422") {
                $rectanglePOS($name="Downstream", $type="package", $instance="422") {
                    $rectanglePOS($soluqiqID="CO_APP_042", $name="METI Store", $zoneColor="#LightPink", $level="Z", $instance="2", $iconic="<&arrow-bottom>", $fullname="METI - Retail Diamond Store")
                    $rectanglePOS($soluqiqID="CO_APP_049", $name="My Store", $zoneColor="#LightCyan", $level="Z", $instance="2", $iconic="<&arrow-circle-bottom>", $fullname="MY STORE - Mobility in store") {
                        usecase "employee efficiency in store" as mystore22
                    }
                }
            }

        }
        $rectanglePOS("IL00105", "Customer order preparation", $level="I") {
            $rectanglePOS($name="Commerce", $type="package", $instance="421") {
                $rectanglePOS($name="Downstream", $type="package", $instance="421") {
                    $rectanglePOS($soluqiqID="CO_APP_042", $name="METI Store", $zoneColor="#LightPink", $level="Z", $instance="1", $iconic="<&arrow-bottom>", $fullname="METI - Retail Diamond Store")
                    $rectanglePOS($soluqiqID="CO_APP_049", $name="My Store", $zoneColor="#LightCyan", $level="Z", $instance="8", $iconic="<&arrow-circle-bottom>", $fullname="MY STORE - Mobility in store") {
                        usecase "employee efficiency in store" as mystore8
                    }
                }
            }

        }
        IL001031 -- IL001041
        IL001041 -- IL001051
        IL001051 -- IL001241

        $rectanglePOS("IL00124", "In Store Transformation", $level="I") {
            $rectanglePOS($name="Commerce", $type="package", $instance="2") {
                $rectanglePOS($name="Upstream", $type="package", $instance="2") {
                    $rectanglePOS($soluqiqID="CO_APP_024", $name="METI Central", $zoneColor="#LightPink", $level="Z", $instance="2", $iconic="<&align-right>", $fullname="METI Central") {
                        usecase "Manage commercial supplier referencing\nManage product referencing for B2B\nMastering product life cycle\nSend supplier and Product to MDM / METI" as MetiCentral3
                    }
                }
            }
            $rectanglePOS($name="Commerce", $type="package", $instance="427") {
                $rectanglePOS($name="Downstream", $type="package", $instance="427") {
                    $rectanglePOS($soluqiqID="CO_APP_042", $name="METI Store", $zoneColor="#LightPink", $level="Z", $instance="7", $iconic="<&arrow-bottom>", $fullname="METI - Retail Diamond Store")
                    $rectanglePOS($soluqiqID="CO_APP_049", $name="My Store", $zoneColor="#LightCyan", $level="Z", $instance="7", $iconic="<&arrow-circle-bottom>", $fullname="MY STORE - Mobility in store") {
                        usecase "employee efficiency in store" as mystore7
                    }
                }
            }

        }
    }
    $rectanglePOS("Q0031", "Procurement & Replenishment", "green", "Q"){
        $rectanglePOS("IL00106", "Allocation management", $level="I") {
            $rectanglePOS($name="Commerce", $type="package", $instance="3") {
                $rectanglePOS($name="Upstream", $type="package", $instance="3") {
                    $rectanglePOS($soluqiqID="CO_APP_024", $name="METI Central", $zoneColor="#LightPink", $level="Z", $instance="3", $iconic="<&align-right>", $fullname="METI Central") {
                        usecase "Manage commercial supplier referencing\nManage product referencing for B2B\nMastering product life cycle\nSend supplier and Product to MDM / METI" as MetiCentral4
                    }
                }
            }
            $rectanglePOS($name="Commerce", $type="package", $instance="14") {
                $rectanglePOS($name="Downstream", $type="package", $instance="3") {
                    $rectanglePOS($soluqiqID="CO_APP_043", $name="METI Supply", $zoneColor="#LightPink", $level="Z", $instance="3", $iconic="<&aperture>", $fullname="METI - Retail Diamond Supply") {
                        usecase "Supply chain from suppliers to customer" as MetiSupply1
                    }
                    $rectanglePOS($soluqiqID="CO_APP_049", $name="My Store", $zoneColor="#LightCyan", $level="Z", $instance="5", $iconic="<&arrow-circle-bottom>", $fullname="MY STORE - Mobility in store") {
                        usecase "employee efficiency in store" as mystore5
                    }
                    $rectanglePOS($soluqiqID="CO_APP_042", $name="METI Store", $zoneColor="#LightPink", $level="Z", $instance="6", $iconic="<&arrow-bottom>", $fullname="METI - Retail Diamond Store")
                }
            }
        CO_APP_0491 - CO_APP_0426
        }
        $rectanglePOS("IL00108", "Replenishment need calculation", $level="I") {
            $rectanglePOS($name="Commerce", $type="package", $instance="19") {
                $rectanglePOS($name="Downstream", $type="package", $instance="8") {
                    $rectanglePOS($soluqiqID="CO_APP_043", $name="METI Supply", $zoneColor="#LightPink", $level="Z", $instance="8", $iconic="<&aperture>", $fullname="METI - Retail Diamond Supply") {
                        usecase "Supply chain from suppliers to customer" as MetiSupply2
                    }
                    $rectanglePOS($soluqiqID="CO_APP_057", $name="Relex", $zoneColor="#Aqua", $level="Z", $instance="2", $iconic="<&audio-spectrum>", $fullname="RELEX - PMS Procurement Management System") {
                        usecase "demand forecast\nReplenishment and dispatch\nInventory Projections\nSpace optimization\nTeam Planning" as Relex1
                    }
                    $rectanglePOS($soluqiqID="CO_APP_034", $name="RPE", $zoneColor="#Bisque", $level="Z", $instance="2", $iconic="<&bar-chart>", $fullname="RPE Replenishment Parameters Engine") {
                        usecase "Store resupply optimisation" as RPE2
                    }
                }
            }
        CO_APP_0572 - CO_APP_0342
        }
        $rectanglePOS("IL00109", "Return to suppliers", $level="I") {
            $rectanglePOS($name="Commerce", $type="package", $instance="18") {
                $rectanglePOS($name="Downstream", $type="package", $instance="7") {
                    $rectanglePOS($soluqiqID="CO_APP_043", $name="METI Supply", $zoneColor="#LightPink", $level="Z", $instance="7", $iconic="<&aperture>", $fullname="METI - Retail Diamond Supply") {
                        usecase "Supply chain from suppliers to customer" as MetiSupply3
                    }
                    $rectanglePOS($soluqiqID="CO_APP_049", $name="My Store", $zoneColor="#LightCyan", $level="Z", $instance="4", $iconic="<&arrow-circle-bottom>", $fullname="MY STORE - Mobility in store") {
                        usecase "employee efficiency in store" as mystore4
                    }
                    $rectanglePOS($soluqiqID="CO_APP_042", $name="METI Store", $zoneColor="#LightPink", $level="Z", $instance="8", $iconic="<&arrow-bottom>", $fullname="METI - Retail Diamond Store")
                }
            }
        CO_APP_0494 - CO_APP_0428
        }
        $rectanglePOS("IL00110", "Return & exchange from customer", $level="I") {
            $rectanglePOS($name="Commerce", $type="package", $instance="17") {
                $rectanglePOS($name="Downstream", $type="package", $instance="6") {
                    $rectanglePOS($soluqiqID="CO_APP_043", $name="METI Supply", $zoneColor="#LightPink", $level="Z", $instance="6", $iconic="<&aperture>", $fullname="METI - Retail Diamond Supply") {
                        usecase "Supply chain from suppliers to customer" as MetiSupply4
                    }
                    $rectanglePOS($soluqiqID="CO_APP_042", $name="METI Store", $zoneColor="#LightPink", $level="Z", $instance="5", $iconic="<&arrow-bottom>", $fullname="METI - Retail Diamond Store")
                    $rectanglePOS($soluqiqID="CO_APP_049", $name="My Store", $zoneColor="#LightCyan", $level="Z", $instance="6", $iconic="<&arrow-circle-bottom>", $fullname="MY STORE - Mobility in store") {
                        usecase "employee efficiency in store" as mystore1
                    }
                }
            }
        CO_APP_0425 - CO_APP_0496
        }
        $rectanglePOS("IL00112", "Procurement order and planning", $level="I") {
            $rectanglePOS($name="Commerce", $type="package", $instance="244") {
                $rectanglePOS($name="Upstream", $type="package", $instance="244") {
                    $rectanglePOS($soluqiqID="CO_APP_024", $name="METI Central", $zoneColor="#LightPink", $level="Z", $instance="4", $iconic="<&align-right>", $fullname="METI Central") {
                        usecase "Manage commercial supplier referencing\nManage product referencing for B2B\nMastering product life cycle\nSend supplier and Product to MDM / METI" as MetiCentral5
                    }
                }
            }
            $rectanglePOS($name="Commerce", $type="package", $instance="435") {
                $rectanglePOS($name="Downstream", $type="package", $instance="435") {
                    $rectanglePOS($soluqiqID="CO_APP_043", $name="METI Supply", $zoneColor="#LightPink", $level="Z", $instance="5", $iconic="<&aperture>", $fullname="METI - Retail Diamond Supply") {
                        usecase "Supply chain from suppliers to customer" as MetiSupply5
                    }
                    $rectanglePOS($soluqiqID="CO_APP_057", $name="Relex", $zoneColor="#Aqua", $level="Z", $instance="3", $iconic="<&audio-spectrum>", $fullname="RELEX - PMS Procurement Management System") {
                        usecase "demand forecast\nReplenishment and dispatch\nInventory Projections\nSpace optimization\nTeam Planning" as Relex2
                    }
                    $rectanglePOS($soluqiqID="CO_APP_042", $name="METI Store", $zoneColor="#LightPink", $level="Z", $instance="3", $iconic="<&arrow-bottom>", $fullname="METI - Retail Diamond Store")
                    $rectanglePOS($soluqiqID="CO_APP_049", $name="My Store", $zoneColor="#LightCyan", $level="Z", $instance="3", $iconic="<&arrow-circle-bottom>", $fullname="MY STORE - Mobility in store") {
                        usecase "employee efficiency in store" as mystore2
                    }
                }
            }
        CO_APP_0573 - CO_APP_0423
        CO_APP_0423 - CO_APP_0493

        }
        $rectanglePOS("IL00111", "Traceability", $level="I")
    }
    IL001061 -- IL001081
    IL001081 -- IL001121
    IL001121 -- IL001101
    IL001101 -- IL001091
    IL001091 -- IL001111
    $rectanglePOS("Q0030", "Goods Provision", "green", "Q"){
        $rectanglePOS("IL00003", "Goods Collection", $level="I") {
            $rectanglePOS($name="Commerce", $type="package", $instance="429") {
                $rectanglePOS($name="Downstream", $type="package", $instance="429") {
                    $rectanglePOS($soluqiqID="CO_APP_042", $name="METI Store", $zoneColor="#LightPink", $level="Z", $instance="9", $iconic="<&arrow-bottom>", $fullname="METI - Retail Diamond Store")
                    $rectanglePOS($soluqiqID="CO_APP_049", $name="My Store", $zoneColor="#LightCyan", $level="Z", $instance="9", $iconic="<&arrow-circle-bottom>", $fullname="MY STORE - Mobility in store") {
                        usecase "employee efficiency in store" as mystore3
                    }
                }
            }

        }
        $rectanglePOS("IL00004", "Goods Delivery", $level="I") {
            $rectanglePOS($name="Commerce", $type="package", $instance="431") {
                $rectanglePOS($name="Downstream", $type="package", $instance="439") {
                    $rectanglePOS($soluqiqID="CO_APP_043", $name="METI Supply", $zoneColor="#LightPink", $level="Z", $instance="9", $iconic="<&aperture>", $fullname="METI - Retail Diamond Supply") {
                        usecase "Supply chain from suppliers to customer" as MetiSupply6
                    }
                    $rectanglePOS($soluqiqID="CO_APP_053", $name="Tesisquare", $zoneColor="#BUSINESS", $level="Z", $instance="3", $iconic="<&ban>", $fullname="TESISQUARE - TMS Transport Management System") {
                        usecase "TMS upstream (goods receiving)\n TMS downstream (goods deliveries)" as Tesi3
                    }
                }
            }

        }
    }
    IL000041 -- IL000031

    $rectanglePOS("Q0100", "Import/Export", "green", "Q"){
    $rectanglePOS("IL00113", "Export Management", $level="I") {
        $rectanglePOS($name="Commerce", $type="package", $instance="6") {
            $rectanglePOS($name="Downstream", $type="package", $instance="1") {
                $rectanglePOS($soluqiqID="CO_APP_043", $name="METI Supply", $zoneColor="#LightPink", $level="Z", $instance="1", $iconic="<&aperture>", $fullname="METI - Retail Diamond Supply") {
                    usecase "Supply chain from suppliers to customer" as MetiSupply7
                }
            }
        }
    }
    $rectanglePOS("IL00114", "Import Management", $level="I") {
        $rectanglePOS($name="Commerce", $type="package", $instance="13") {
            $rectanglePOS($name="Downstream", $type="package", $instance="2") {
                $rectanglePOS($soluqiqID="CO_APP_043", $name="METI Supply", $zoneColor="#LightPink", $level="Z", $instance="2", $iconic="<&aperture>", $fullname="METI - Retail Diamond Supply") {
                    usecase "Supply chain from suppliers to customer" as MetiSupply8
                }
            }
        }
    }
    IL001131 -- IL001141

}
@enduml

@startuml Z008
!include include/_posparam.plantuml


$rectanglePOS("Z008", "Customer Orders Management", "green", "Z" ) {
    $rectanglePOS("Q0048", "Customer promise calculation", "green", "Q")
    $rectanglePOS("Q0053", "Order monitoring and execution", "green", "Q")
}

@enduml