@startuml Process
skinparam handwritten true
skinparam componentStyle rectangle
!theme plain

package "Reference a Product" {

[process 1] as p1
[process 2] as p2
[Process 3] as p3

p1 -> p2 : then
p2 -> p3 : then


}

@enduml

@startuml Several Processes
skinparam handwritten true
skinparam componentStyle rectangle
!theme plain



card "Reference a product" as c1 {

[process 1] as p1
[process 2] as p2
[Process 3] as p3

p1 -r-> p2 : then
p2 -r-> p3 : then

[myApp ] as m1
[otherApp ] as m2

p1 --> m2 : served by
p2 ---> m2 : served by


p1 --> m1 : served by
p2 --> m1 : served by
p3 ---> m1 : served by


m1 -l--> m2 : integration pattern
m1 -l--> m2 : information flow





}


card "Other need fullfilled" as c2 {

[process 1c] as p4
[process 2c] as p5
[Process 3c] as p6

p4 -> p5 : then
p5 -> p6 : then


}

c1 ---> c2 : information flow\n(integration pattern)
c2 -> c1

@enduml


@startuml Core Model
skinparam handwritten true
skinparam componentStyle rectangle
!theme plain


card "Customer Diamond" as c1 {
    
    card need1 {
        [processes] as p1
        [Business Applications] as b1
        b1 <-u- p1 : served by
    }

    card need2 {
        [processes] as p1a
        [Business Applications] as b1a
        b1a <-u- p1a : served by
    }
}

card "Retail Diamond" as c2 {
    
    card "need x" {
        [processes] as p2
        [Business Applications] as b2
        b2 <-u- p2 : served by
    }
}

card "Finance Diamond" as c3 {
    
    card "need y" {
    
        [processes] as p3
        [Business Applications] as b3
        b3 <-u- p3 : served by
    }
}

c1 -> c2 
c2 -l-> c1 
c1 -> c3 : information flow\n(integration pattern)
c3 -l-> c1
c2 -> c3
c3 -l-> c2

card repositories as c4 {

database r1
database r2

}

c4 -u--> c1 : information flow\n(integration pattern)
c4 -u--> c2 : information flow\n(integration pattern)
c4 -u---> c3 : information flow\n(integration pattern)


@enduml


@startuml 3 processes
skinparam handwritten true
skinparam componentStyle rectangle
!theme plain

card "Other need fullfilled" as c3 {

[process 1a] as p7
[process 2a] as p8
[Process 3a] as p9

p7 -> p8 : then
p8 -> p9 : then


}


card "__**Reference a product**__" as c1 {

[process 1] as p1
[process 2] as p2
[Process 3] as p3

p1 -> p2 : then
p2 -> p3 : then

}


card "Other need fullfilled" as c2 {

[process 1c] as p4
[process 2c] as p5
[Process 3c] as p6

p4 -> p5 : then
p5 -> p6 : then


}


@enduml


@startuml top bottom
skinparam handwritten true
skinparam componentStyle rectangle
!theme plain

[Need : Reference a product] as n1


card "Reference a product" as c1 {

[process 1] as p1
[process 2] as p2
[Process 3] as p3

p1 -> p2 : then
p2 -> p3 : then

}

n1 --> c1 : realized by

[Business Appplications] as b1

c1 --> b1 : served by

[Repositories] as r1

b1 --> r1 : served by
@enduml