@startuml RepositoryLinks
!include include/_posparam.plantuml

$rectanglePOS("Z010", "Data Management (Data as an asset)", "brown", "Z" ) {
    $rectanglePOS("Q0091", "Repositories", "brown", "Q") {
        $rectanglePOS("IL00012", "Nomenclature", $level="I") {
            $sbbSoluQIQ("CO_APP_007", "Nomenclature", "#red", "1", $type="database", $comment="ready to deploy")
        }
    }
}

$rectanglePOS("Z005", "Supply chain", "green", "Z" ) {
    $rectanglePOS("Q0029", "Store Back-Office", "green", "Q"){
        $rectanglePOS("IL00124", "In Store Transformation", $level="I") {
            $sbbSoluQIQ("CO_APP_039", "Meti_Central", "#Whitesmoke", "1")
        }
    }
    $rectanglePOS("Q0031", "Procurement & Replenishment", "green", "Q"){
        $rectanglePOS("IL00106", "Allocation management", $level="I") {
            $sbbSoluQIQ("CO_APP_039", "Meti_Central", "#Whitesmoke", "2")
        }
        $rectanglePOS("IL00112", "Procurement order and planning", $level="I") {
            $sbbSoluQIQ("CO_APP_039", "Meti_Central", "#Whitesmoke", "3")
        }
    }
}

$rectanglePOS("Z001", "Direct and indirect purchase", "green", "Z" ) {
    $rectanglePOS("Q0105", "Direct Purchase",  "green", "Q"){
        $rectanglePOS("IL00133", "Supplier referencing", $level="I") {
            $sbbSoluQIQ("CO_APP_039", "Meti_Central", "#Whitesmoke", "4")
        }
        $rectanglePOS("IL00011", "Product Referencing", $level="I") {
            $sbbSoluQIQ("CO_APP_039", "Meti_Central", "#Whitesmoke", "7")
        }

    }
}   

$rectanglePOS("Z007", "Offer (products & services)", "green", "Z" ) {
    $rectanglePOS("Q0040", "Partners Management", "green", "Q"){
        $rectanglePOS("IL00094", "B2B sell / Transfer pricing management", $level="I") {
            $sbbSoluQIQ("CO_APP_039", "Meti_Central", "#Whitesmoke", "5")
        }
    }
    $rectanglePOS("Q0042", "Offer to Customers", "green", "Q"){
        $rectanglePOS("IL00088", "Selling price management", $level="I") {
            $sbbSoluQIQ("CO_APP_039", "Meti_Central", "#Whitesmoke", "6")
        }
    }
}

CO_APP_0071 -d-> CO_APP_0391
CO_APP_0071 -d-> CO_APP_0392
CO_APP_0071 -d-> CO_APP_0393
CO_APP_0071 -d-> CO_APP_0394
CO_APP_0071 -d-> CO_APP_0395
CO_APP_0071 -d-> CO_APP_0396
CO_APP_0071 -d-> CO_APP_0397

@enduml