@startuml
' https://textik.com/#1ff78363ce05d72e
ditaa
 +---------------------------+ 
 |                           | 
 |                           | 
 |    Presentation layer     | 
 |                           | 
 +---------------------------+ 
               |               
               |               
               v               
 +----------------------------+
 |                            |
 |                            |
 |     Business Logic         |
 |                            |
 +----------------------------+
               |               
               v               
 +----------------------------+
 |                            |
 |    Database Layer          |
 |                            |
 |                            |
 +----------------------------+
@enduml