@startuml P
skinparam DefaultTextAlignment center
allow_mixing
skinparam Nodesep 1
skinparam Ranksep 2
skinparam ComponentStyle rectangle
skinparam ArrowThickness 0

' excel function
' =CONCATENATE("$rectanglePOS($soluqiqID=""",B2,""", $name=""",C2,""", $zoneColor=""#LightGray"", $level=""Z"", $instance=""1"", $iconic=""none"", $fullname=""",D2,""")")

!procedure $rectanglePOS($soluqiqID="tdb", $name="none", $zoneColor="#LightGray", $level=".", $instance="1", $iconic="none", $fullname=".", $type="component")
    '''
    ''' Procedure pour dessiner les différents niveaux du framework fonctionnel
    ''' Zone / Quartier / ilot / SBB / Function SBB
    '''
    ''' iconic must be one of present here : https://plantuml.com/openiconic
    !$colorGreenZone = "#85C21F"
    !$colorGreenQuarter = "#EAF8DA"
    !$colorPurpleZone = "#AC6083"
    !$colorPurpleQuarter = "#F9E6E7"
    !$colorBrownZone = "#7A4D26"
    !$colorBrownQuarter = "#F9E6E7"
    !$colorRedZone = "#CC3C45"
    !$colorRedQuarter = "#F9E6E7"
    !$colorDefaultBlock = "#FFFFE8"

    !$fullnamefontsize = "11"

    !if ($zoneColor == "green") && ($level == "Z")
        !$color = $colorGreenZone
        !elseif ($zoneColor == "green") && ($level == "Q")
            !$color = $colorGreenQuarter
        !elseif ($zoneColor == "red") && ($level == "Z")
            !$color = $colorRedZone
        !elseif ($zoneColor == "red") && ($level == "Q")
            !$color = $colorRedQuarter
        !elseif ($zoneColor == "purple") && ($level == "Z")
            !$color = $colorPurpleZone
        !elseif ($zoneColor == "purple") && ($level == "Q")
            !$color = $colorPurpleQuarter
        !elseif ($zoneColor == "brown") && ($level == "Z")
            !$color = $colorBrownZone
        !elseif ($zoneColor == "brown") && ($level == "Q")
            !$color = $colorBrownQuarter
        !elseif ($zoneColor == "none") && ($level == "Z")
            !$color = DarkBlue
        !elseif ($level == "I")
            !$color = $colorDefaultBlock
        !else
            !$color = $zoneColor
    !endif

    !if ($type == "package")
        $type $name as $name##$instance
    !endif

    !if ($type == "component")
        !if ($iconic == "none")
            $type "$name##\n<size:$fullnamefontsize>$fullname" as $soluqiqID##$instance <<$soluqiqID>> $color
        !else
            $type "$iconic\n$name##\n<size:$fullnamefontsize>$fullname" as $soluqiqID##$instance <<$soluqiqID>> $color
        !endif
    !endif
!endprocedure

!procedure $sbbSoluQIQ($soluqiqID="tdb", $name="none", $sbbColor="none", $instance="1", $version="not provided", $comment="", $type="component")
    $type "$name" as $soluqiqID##$instance <<$soluqiqID>> $sbbColor
!endprocedure


@enduml