@startuml P
skinparam DefaultTextAlignment center
allow_mixing
skinparam Nodesep 2
skinparam ComponentStyle rectangle
skinparam ArrowThickness 0

' excel function
' =CONCATENER("$rectanglePOS($soluqiqID=""";B2;""", $name=""";C2;""", $zoneColor=""#FFFFE8"", $level=""Z"", $instance=""1"")")

!procedure $rectanglePOS($soluqiqID="tdb", $name="none", $zoneColor="#LightGray", $level="Z", $instance="1")
    '''
    ''' Procedure pour dessiner les différents niveaux du framework fonctionnel
    ''' Zone / Quartier / ilot / SBB / Function SBB
    '''
    !$colorGreenZone = "#85C21F"
    !$colorGreenQuarter = "#EAF8DA"
    !$colorPurpleZone = "#AC6083"
    !$colorPurpleQuarter = "#F9E6E7"
    !$colorBrownZone = "#7A4D26"
    !$colorBrownQuarter = "#F9E6E7"
    !$colorRedZone = "#CC3C45"
    !$colorRedQuarter = "#F9E6E7"
    !$colorDefaultBlock = "#FFFFE8"

    !if ($zoneColor == "green") && ($level == "Z")
        !$color = $colorGreenZone
    !elseif ($zoneColor == "green") && ($level == "Q")
        !$color = $colorGreenQuarter
    !elseif ($zoneColor == "red") && ($level == "Z")
        !$color = $colorRedZone
    !elseif ($zoneColor == "red") && ($level == "Q")
        !$color = $colorRedQuarter
    !elseif ($zoneColor == "purple") && ($level == "Z")
        !$color = $colorPurpleZone
    !elseif ($zoneColor == "purple") && ($level == "Q")
        !$color = $colorPurpleQuarter
    !elseif ($zoneColor == "brown") && ($level == "Z")
        !$color = $colorBrownZone
    !elseif ($zoneColor == "brown") && ($level == "Q")
        !$color = $colorBrownQuarter
    !elseif ($zoneColor == "none") && ($level == "Z")
        !$color = DarkBlue
    !elseif ($level == "I")
        !$color = $colorDefaultBlock
    !else
        !$color = $zoneColor
    !endif

    component "$name" as $soluqiqID##$instance <<$soluqiqID>> $color
!endprocedure

!procedure $sbbSoluQIQ($soluqiqID="tdb", $name="none", $sbbColor="none", $instance="1", $version="not provided", $comment="", $type="component")
    ''' DEPRECATED
    '''
    ''' Procedure pour dessiner les SBB.
    ''' $sbbCOlor : doit avoir # devant la couleur
    ''' $instance : necessaire de l'incrementer pour chaque SBB qui apparait plus d'une fois dans le diagramme
    ''' $comment : commentaire libre
    ''' $type : doit être un objet du diagramme de composant : component, database, interface, package, node, folder, frame, cloud
    '''
    $type "$name" as $soluqiqID##$instance <<$soluqiqID>> $sbbColor
!endprocedure


@enduml